### ISSUE TITLE
Add more examples

### ISSUE THREAD

**Issue by cyruzin** [cyruzin/golang-study#1]

**Comment by luhego** [comment]
I am adding an example of unit testing.

**Comment by cyruzin** [comment]
Merged.

**Comment by samit22** [comment]
I will be adding WaitGroups for goroutines.

**Comment by cyruzin** [comment]
> I will be adding WaitGroups for goroutines.

Merged.

**Comment by nicoleyson** [comment]
Added https://github.com/cyruzin/golang-study/pull/7
